In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import numpy as np
swvec = np.load("../output/Trinity_normal/swvec.npy")
ptvec = np.load("../output/Trinity_normal/ptvec.npy")
pricevec = np.load("../output/Trinity_normal/pricevec.npy")

array([1080.6056357 ,  211.11518727,   65.80871479, ...,  179.5097903 ,
        241.37572507,  179.30369356])

In [12]:
print(np.load("../output/Bottleneck/Trinity_normal/swvec.npy"))


[45837.16614936 44352.72960829 44273.01083862 44214.78330861
 44254.96035654 44252.91819954 44236.24684605 44249.03766922
 44231.6938413  44234.53826566]


In [ ]:
import numpy as np

util =  np.load("../output/tmp_BO_Bottleneck_normal/util.npy")

util


array([1101.09173217,  211.43822805,   66.06783804, ...,  191.251502  ,
        248.36975687,  181.18485604])

In [1]:
20035/7500

2.671333333333333

In [ ]:
util-NT

In [6]:
ub = np.load("../output/tmp_BO_Bottleneck_normal/userBenefits.npy")

array([20.48609646,  0.32304078,  0.25912326, ..., 11.74171169,
        6.9940318 ,  1.88116248])

In [7]:
np.load("../output/tmp_BO_Bottleneck_normal/RR.npy")

array(-18.347351)

In [6]:
np.load("../output/MFD/Trinity/ttvec.npy")

array([35.88445609, 34.83952182, 34.79488364, 34.76435737, 34.69855979,
       34.64373209, 34.5805685 , 34.54933439, 34.48231498, 34.45866835,
       34.40600345, 34.37744003, 34.34563663, 34.3227536 , 34.27537322,
       34.25271943, 34.23930831, 34.22523859, 34.19858631, 34.18601462,
       34.17837193, 34.16272751, 34.13397566, 34.12855106, 34.10125419,
       34.0893958 , 34.07443538, 34.0747346 , 34.06133021, 34.06048535])